name: build

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install texlive-full

    - name: Build
      run: make
